# If you come from bash you might have to change your $PATH.
export PATH="/home/matus/Documents/sublime_text_3_build_3207_x64/sublime_text_3:$PATH"
export PATH="/home/matus/.cargo/bin:/home/matus/.local/bin:$PATH"

# Path to your oh-my-zsh installation.
export ZSH="/home/matus/.oh-my-zsh"

# Set numper of cores for makepkg
MAKEFLAGS="-j$(nproc)"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="powerlevel10k/powerlevel10k"

export POWERLEVEL9K_VCS_SHORTEN_LENGTH=4
export POWERLEVEL9K_VCS_SHORTEN_MIN_LENGTH=11
export POWERLEVEL9K_VCS_SHORTEN_STRATEGY="truncate_middle"
export POWERLEVEL9K_VCS_SHORTEN_DELIMITER=".."

export XKB_DEFAULT_LAYOUT=us,sk
export XKB_DEFAULT_OPTIONS=grp:lctrl_lshift_toggle

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git web-search man docker copybuffer colored-man-pages zsh-autosuggestions zsh-syntax-highlighting zsh_reload)
# (virtualenv)
# (omz-git) Modify the console prompt play more nicely with our branch naming conventions
# (z) Tracks your most used directories, based on 'frequency'.
# (dircycle) => This plugin enables directory navigation similar to using back and forward on browsers or common file explorers like Finder or Nautilus.
# <docker> => This plugin adds auto-completion for docker.
# <wd> (warp directory) lets you jump to custom directories
# <web-search> => Adds aliases for searching with Google, Wiki, Bing, YouTube and other popular services.
# <man> Esc + man => add man before the previous command to see the manual for this command
# <colored-man-pages> => This plugin adds colors to man pages.
# <copybuffer> Ctrl-o => copies the text that is currently typed in the command line ($BUFFER) to the system clipboard
# (copyfile) => Puts the contents of a file in your system clipboard so you can paste it anywhere.
# (thefuck) Esc + Esc => correct previous console command
# (jira) CLI support for JIRA interaction - https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/jira
# (systemadmin) This plugin adds a series of aliases and functions which make a System Administrator's life easier - https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/systemadmin
# <zsh-syntax-highlighting> It provides syntax highlighting for the shell zsh.
# <zsh-autosuggestions> It suggests commands as you type based on history and completions
# <zsh_reload> src => The zsh_reload plugin defines a function to reload the zsh session with just a few keystrokes

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
[[ -f ~/.aliases.zsh ]] && source ~/.aliases.zsh

# Set default Editor
# If emacs is installed use that option otherwise select nano as default editor
export EDITOR="emacsclient -t"

# Set default blocksize for ls, df, du
export BLOCKSIZE=1k


################ zoxide begin ####################
_zoxide_precmd() {
    zoxide add
}

[[ -n "${precmd_functions[(r)_zoxide_precmd]}" ]] || {
    precmd_functions+=(_zoxide_precmd)
}

z() {
    if [ $# -ne 0 ]; then
        _Z_RESULT=$(zoxide query "$@")
        case $_Z_RESULT in
            "query: "*)
                cd "${_Z_RESULT:7}"
                ;;
            *)
                echo "${_Z_RESULT}"
                ;;
        esac
    fi
}

alias zi="z -i"

alias za="zoxide add"
alias zq="zoxide query"
alias zr="zoxide remove"
################ zoxide end ####################

eval "$(direnv hook zsh)"

# If file local configuration exists, load it
[[ -f ~/.local_bashrc ]] && source ~/.local_bashrc

# Include functions
[[ -f ~/.functions.zsh ]] && source ~/.functions.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh
